#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Dataguard_test")]
	public partial class EntidadesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertProducto(Producto instance);
    partial void UpdateProducto(Producto instance);
    partial void DeleteProducto(Producto instance);
    partial void InsertDetalle_factura(Detalle_factura instance);
    partial void UpdateDetalle_factura(Detalle_factura instance);
    partial void DeleteDetalle_factura(Detalle_factura instance);
    partial void InsertProducto1(Producto1 instance);
    partial void UpdateProducto1(Producto1 instance);
    partial void DeleteProducto1(Producto1 instance);
    partial void InsertTb_cliente(Tb_cliente instance);
    partial void UpdateTb_cliente(Tb_cliente instance);
    partial void DeleteTb_cliente(Tb_cliente instance);
    partial void InsertTb_Factura(Tb_Factura instance);
    partial void UpdateTb_Factura(Tb_Factura instance);
    partial void DeleteTb_Factura(Tb_Factura instance);
    #endregion
		
		public EntidadesDataContext() : 
				base(global::Modelo.Properties.Settings.Default.conection, mappingSource)
		{
			OnCreated();
		}
		
		public EntidadesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EntidadesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EntidadesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EntidadesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Producto> Producto
		{
			get
			{
				return this.GetTable<Producto>();
			}
		}
		
		public System.Data.Linq.Table<Detalle_factura> Detalle_factura
		{
			get
			{
				return this.GetTable<Detalle_factura>();
			}
		}
		
		public System.Data.Linq.Table<Producto1> Producto1
		{
			get
			{
				return this.GetTable<Producto1>();
			}
		}
		
		public System.Data.Linq.Table<Tb_cliente> Tb_cliente
		{
			get
			{
				return this.GetTable<Tb_cliente>();
			}
		}
		
		public System.Data.Linq.Table<Tb_Factura> Tb_Factura
		{
			get
			{
				return this.GetTable<Tb_Factura>();
			}
		}
		
		public System.Data.Linq.Table<View_Detallefactura> View_Detallefactura
		{
			get
			{
				return this.GetTable<View_Detallefactura>();
			}
		}
		
		public System.Data.Linq.Table<View_TOTAL_A_PAGAR> View_TOTAL_A_PAGAR
		{
			get
			{
				return this.GetTable<View_TOTAL_A_PAGAR>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Producto")]
	public partial class Producto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ProductoId;
		
		private string _Nombre;
		
		private System.Nullable<double> _Precio;
		
		private string _Descripcion;
		
		private System.Nullable<int> _Detalle;
		
		private EntityRef<Detalle_factura> _Detalle_factura;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnProductoIdChanging(int value);
    partial void OnProductoIdChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnPrecioChanging(System.Nullable<double> value);
    partial void OnPrecioChanged();
    partial void OnDescripcionChanging(string value);
    partial void OnDescripcionChanged();
    partial void OnDetalleChanging(System.Nullable<int> value);
    partial void OnDetalleChanged();
    #endregion
		
		public Producto()
		{
			this._Detalle_factura = default(EntityRef<Detalle_factura>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductoId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ProductoId
		{
			get
			{
				return this._ProductoId;
			}
			set
			{
				if ((this._ProductoId != value))
				{
					this.OnProductoIdChanging(value);
					this.SendPropertyChanging();
					this._ProductoId = value;
					this.SendPropertyChanged("ProductoId");
					this.OnProductoIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Precio", DbType="Float")]
		public System.Nullable<double> Precio
		{
			get
			{
				return this._Precio;
			}
			set
			{
				if ((this._Precio != value))
				{
					this.OnPrecioChanging(value);
					this.SendPropertyChanging();
					this._Precio = value;
					this.SendPropertyChanged("Precio");
					this.OnPrecioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(50)")]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this.OnDescripcionChanging(value);
					this.SendPropertyChanging();
					this._Descripcion = value;
					this.SendPropertyChanged("Descripcion");
					this.OnDescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Detalle", DbType="Int")]
		public System.Nullable<int> Detalle
		{
			get
			{
				return this._Detalle;
			}
			set
			{
				if ((this._Detalle != value))
				{
					if (this._Detalle_factura.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnDetalleChanging(value);
					this.SendPropertyChanging();
					this._Detalle = value;
					this.SendPropertyChanged("Detalle");
					this.OnDetalleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Detalle_factura_Producto", Storage="_Detalle_factura", ThisKey="Detalle", OtherKey="DetallID", IsForeignKey=true)]
		public Detalle_factura Detalle_factura
		{
			get
			{
				return this._Detalle_factura.Entity;
			}
			set
			{
				Detalle_factura previousValue = this._Detalle_factura.Entity;
				if (((previousValue != value) 
							|| (this._Detalle_factura.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Detalle_factura.Entity = null;
						previousValue.Producto.Remove(this);
					}
					this._Detalle_factura.Entity = value;
					if ((value != null))
					{
						value.Producto.Add(this);
						this._Detalle = value.DetallID;
					}
					else
					{
						this._Detalle = default(Nullable<int>);
					}
					this.SendPropertyChanged("Detalle_factura");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Detalle_factura")]
	public partial class Detalle_factura : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _DetallID;
		
		private System.Nullable<int> _Factura;
		
		private System.Nullable<int> _Productos;
		
		private EntitySet<Producto> _Producto;
		
		private EntitySet<Producto1> _Producto1;
		
		private EntityRef<Tb_Factura> _Tb_Factura;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDetallIDChanging(int value);
    partial void OnDetallIDChanged();
    partial void OnFacturaChanging(System.Nullable<int> value);
    partial void OnFacturaChanged();
    partial void OnProductosChanging(System.Nullable<int> value);
    partial void OnProductosChanged();
    #endregion
		
		public Detalle_factura()
		{
			this._Producto = new EntitySet<Producto>(new Action<Producto>(this.attach_Producto), new Action<Producto>(this.detach_Producto));
			this._Producto1 = new EntitySet<Producto1>(new Action<Producto1>(this.attach_Producto1), new Action<Producto1>(this.detach_Producto1));
			this._Tb_Factura = default(EntityRef<Tb_Factura>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DetallID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int DetallID
		{
			get
			{
				return this._DetallID;
			}
			set
			{
				if ((this._DetallID != value))
				{
					this.OnDetallIDChanging(value);
					this.SendPropertyChanging();
					this._DetallID = value;
					this.SendPropertyChanged("DetallID");
					this.OnDetallIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Factura", DbType="Int")]
		public System.Nullable<int> Factura
		{
			get
			{
				return this._Factura;
			}
			set
			{
				if ((this._Factura != value))
				{
					if (this._Tb_Factura.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnFacturaChanging(value);
					this.SendPropertyChanging();
					this._Factura = value;
					this.SendPropertyChanged("Factura");
					this.OnFacturaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Productos", DbType="Int")]
		public System.Nullable<int> Productos
		{
			get
			{
				return this._Productos;
			}
			set
			{
				if ((this._Productos != value))
				{
					this.OnProductosChanging(value);
					this.SendPropertyChanging();
					this._Productos = value;
					this.SendPropertyChanged("Productos");
					this.OnProductosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Detalle_factura_Producto", Storage="_Producto", ThisKey="DetallID", OtherKey="Detalle")]
		public EntitySet<Producto> Producto
		{
			get
			{
				return this._Producto;
			}
			set
			{
				this._Producto.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Detalle_factura_Producto1", Storage="_Producto1", ThisKey="DetallID", OtherKey="Detalle")]
		public EntitySet<Producto1> Producto1
		{
			get
			{
				return this._Producto1;
			}
			set
			{
				this._Producto1.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tb_Factura_Detalle_factura", Storage="_Tb_Factura", ThisKey="Factura", OtherKey="FacturaId", IsForeignKey=true)]
		public Tb_Factura Tb_Factura
		{
			get
			{
				return this._Tb_Factura.Entity;
			}
			set
			{
				Tb_Factura previousValue = this._Tb_Factura.Entity;
				if (((previousValue != value) 
							|| (this._Tb_Factura.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tb_Factura.Entity = null;
						previousValue.Detalle_factura.Remove(this);
					}
					this._Tb_Factura.Entity = value;
					if ((value != null))
					{
						value.Detalle_factura.Add(this);
						this._Factura = value.FacturaId;
					}
					else
					{
						this._Factura = default(Nullable<int>);
					}
					this.SendPropertyChanged("Tb_Factura");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Producto(Producto entity)
		{
			this.SendPropertyChanging();
			entity.Detalle_factura = this;
		}
		
		private void detach_Producto(Producto entity)
		{
			this.SendPropertyChanging();
			entity.Detalle_factura = null;
		}
		
		private void attach_Producto1(Producto1 entity)
		{
			this.SendPropertyChanging();
			entity.Detalle_factura = this;
		}
		
		private void detach_Producto1(Producto1 entity)
		{
			this.SendPropertyChanging();
			entity.Detalle_factura = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Producto")]
	public partial class Producto1 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ProductoId;
		
		private string _Nombre;
		
		private System.Nullable<double> _Precio;
		
		private string _Descripcion;
		
		private System.Nullable<int> _Detalle;
		
		private EntityRef<Detalle_factura> _Detalle_factura;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnProductoIdChanging(int value);
    partial void OnProductoIdChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnPrecioChanging(System.Nullable<double> value);
    partial void OnPrecioChanged();
    partial void OnDescripcionChanging(string value);
    partial void OnDescripcionChanged();
    partial void OnDetalleChanging(System.Nullable<int> value);
    partial void OnDetalleChanged();
    #endregion
		
		public Producto1()
		{
			this._Detalle_factura = default(EntityRef<Detalle_factura>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductoId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ProductoId
		{
			get
			{
				return this._ProductoId;
			}
			set
			{
				if ((this._ProductoId != value))
				{
					this.OnProductoIdChanging(value);
					this.SendPropertyChanging();
					this._ProductoId = value;
					this.SendPropertyChanged("ProductoId");
					this.OnProductoIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Precio", DbType="Float")]
		public System.Nullable<double> Precio
		{
			get
			{
				return this._Precio;
			}
			set
			{
				if ((this._Precio != value))
				{
					this.OnPrecioChanging(value);
					this.SendPropertyChanging();
					this._Precio = value;
					this.SendPropertyChanged("Precio");
					this.OnPrecioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(50)")]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this.OnDescripcionChanging(value);
					this.SendPropertyChanging();
					this._Descripcion = value;
					this.SendPropertyChanged("Descripcion");
					this.OnDescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Detalle", DbType="Int")]
		public System.Nullable<int> Detalle
		{
			get
			{
				return this._Detalle;
			}
			set
			{
				if ((this._Detalle != value))
				{
					if (this._Detalle_factura.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnDetalleChanging(value);
					this.SendPropertyChanging();
					this._Detalle = value;
					this.SendPropertyChanged("Detalle");
					this.OnDetalleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Detalle_factura_Producto1", Storage="_Detalle_factura", ThisKey="Detalle", OtherKey="DetallID", IsForeignKey=true)]
		public Detalle_factura Detalle_factura
		{
			get
			{
				return this._Detalle_factura.Entity;
			}
			set
			{
				Detalle_factura previousValue = this._Detalle_factura.Entity;
				if (((previousValue != value) 
							|| (this._Detalle_factura.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Detalle_factura.Entity = null;
						previousValue.Producto1.Remove(this);
					}
					this._Detalle_factura.Entity = value;
					if ((value != null))
					{
						value.Producto1.Add(this);
						this._Detalle = value.DetallID;
					}
					else
					{
						this._Detalle = default(Nullable<int>);
					}
					this.SendPropertyChanged("Detalle_factura");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tb_cliente")]
	public partial class Tb_cliente : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Idusuario;
		
		private string _Nombre;
		
		private string _Apellido;
		
		private string _NIT;
		
		private EntitySet<Tb_Factura> _Tb_Factura;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdusuarioChanging(int value);
    partial void OnIdusuarioChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnApellidoChanging(string value);
    partial void OnApellidoChanged();
    partial void OnNITChanging(string value);
    partial void OnNITChanged();
    #endregion
		
		public Tb_cliente()
		{
			this._Tb_Factura = new EntitySet<Tb_Factura>(new Action<Tb_Factura>(this.attach_Tb_Factura), new Action<Tb_Factura>(this.detach_Tb_Factura));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Idusuario", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Idusuario
		{
			get
			{
				return this._Idusuario;
			}
			set
			{
				if ((this._Idusuario != value))
				{
					this.OnIdusuarioChanging(value);
					this.SendPropertyChanging();
					this._Idusuario = value;
					this.SendPropertyChanged("Idusuario");
					this.OnIdusuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="NChar(10)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellido", DbType="NChar(10)")]
		public string Apellido
		{
			get
			{
				return this._Apellido;
			}
			set
			{
				if ((this._Apellido != value))
				{
					this.OnApellidoChanging(value);
					this.SendPropertyChanging();
					this._Apellido = value;
					this.SendPropertyChanged("Apellido");
					this.OnApellidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NIT", DbType="NChar(10)")]
		public string NIT
		{
			get
			{
				return this._NIT;
			}
			set
			{
				if ((this._NIT != value))
				{
					this.OnNITChanging(value);
					this.SendPropertyChanging();
					this._NIT = value;
					this.SendPropertyChanged("NIT");
					this.OnNITChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tb_cliente_Tb_Factura", Storage="_Tb_Factura", ThisKey="Idusuario", OtherKey="Cliente")]
		public EntitySet<Tb_Factura> Tb_Factura
		{
			get
			{
				return this._Tb_Factura;
			}
			set
			{
				this._Tb_Factura.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Tb_Factura(Tb_Factura entity)
		{
			this.SendPropertyChanging();
			entity.Tb_cliente = this;
		}
		
		private void detach_Tb_Factura(Tb_Factura entity)
		{
			this.SendPropertyChanging();
			entity.Tb_cliente = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tb_Factura")]
	public partial class Tb_Factura : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _FacturaId;
		
		private string _Encabezado;
		
		private int _Cliente;
		
		private int _Detalle;
		
		private System.Nullable<System.DateTime> _fecha;
		
		private EntitySet<Detalle_factura> _Detalle_factura;
		
		private EntityRef<Tb_cliente> _Tb_cliente;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnFacturaIdChanging(int value);
    partial void OnFacturaIdChanged();
    partial void OnEncabezadoChanging(string value);
    partial void OnEncabezadoChanged();
    partial void OnClienteChanging(int value);
    partial void OnClienteChanged();
    partial void OnDetalleChanging(int value);
    partial void OnDetalleChanged();
    partial void OnfechaChanging(System.Nullable<System.DateTime> value);
    partial void OnfechaChanged();
    #endregion
		
		public Tb_Factura()
		{
			this._Detalle_factura = new EntitySet<Detalle_factura>(new Action<Detalle_factura>(this.attach_Detalle_factura), new Action<Detalle_factura>(this.detach_Detalle_factura));
			this._Tb_cliente = default(EntityRef<Tb_cliente>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacturaId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int FacturaId
		{
			get
			{
				return this._FacturaId;
			}
			set
			{
				if ((this._FacturaId != value))
				{
					this.OnFacturaIdChanging(value);
					this.SendPropertyChanging();
					this._FacturaId = value;
					this.SendPropertyChanged("FacturaId");
					this.OnFacturaIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Encabezado", DbType="VarChar(50)")]
		public string Encabezado
		{
			get
			{
				return this._Encabezado;
			}
			set
			{
				if ((this._Encabezado != value))
				{
					this.OnEncabezadoChanging(value);
					this.SendPropertyChanging();
					this._Encabezado = value;
					this.SendPropertyChanged("Encabezado");
					this.OnEncabezadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cliente", DbType="Int NOT NULL")]
		public int Cliente
		{
			get
			{
				return this._Cliente;
			}
			set
			{
				if ((this._Cliente != value))
				{
					if (this._Tb_cliente.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnClienteChanging(value);
					this.SendPropertyChanging();
					this._Cliente = value;
					this.SendPropertyChanged("Cliente");
					this.OnClienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Detalle", DbType="Int NOT NULL")]
		public int Detalle
		{
			get
			{
				return this._Detalle;
			}
			set
			{
				if ((this._Detalle != value))
				{
					this.OnDetalleChanging(value);
					this.SendPropertyChanging();
					this._Detalle = value;
					this.SendPropertyChanged("Detalle");
					this.OnDetalleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha", DbType="DateTime")]
		public System.Nullable<System.DateTime> fecha
		{
			get
			{
				return this._fecha;
			}
			set
			{
				if ((this._fecha != value))
				{
					this.OnfechaChanging(value);
					this.SendPropertyChanging();
					this._fecha = value;
					this.SendPropertyChanged("fecha");
					this.OnfechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tb_Factura_Detalle_factura", Storage="_Detalle_factura", ThisKey="FacturaId", OtherKey="Factura")]
		public EntitySet<Detalle_factura> Detalle_factura
		{
			get
			{
				return this._Detalle_factura;
			}
			set
			{
				this._Detalle_factura.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tb_cliente_Tb_Factura", Storage="_Tb_cliente", ThisKey="Cliente", OtherKey="Idusuario", IsForeignKey=true)]
		public Tb_cliente Tb_cliente
		{
			get
			{
				return this._Tb_cliente.Entity;
			}
			set
			{
				Tb_cliente previousValue = this._Tb_cliente.Entity;
				if (((previousValue != value) 
							|| (this._Tb_cliente.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tb_cliente.Entity = null;
						previousValue.Tb_Factura.Remove(this);
					}
					this._Tb_cliente.Entity = value;
					if ((value != null))
					{
						value.Tb_Factura.Add(this);
						this._Cliente = value.Idusuario;
					}
					else
					{
						this._Cliente = default(int);
					}
					this.SendPropertyChanged("Tb_cliente");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Detalle_factura(Detalle_factura entity)
		{
			this.SendPropertyChanging();
			entity.Tb_Factura = this;
		}
		
		private void detach_Detalle_factura(Detalle_factura entity)
		{
			this.SendPropertyChanging();
			entity.Tb_Factura = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.View_Detallefactura")]
	public partial class View_Detallefactura
	{
		
		private int _Idusuario;
		
		private string _Nombre;
		
		private string _productos;
		
		private System.Nullable<double> _Precio;
		
		private string _Descripcion;
		
		public View_Detallefactura()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Idusuario", DbType="Int NOT NULL")]
		public int Idusuario
		{
			get
			{
				return this._Idusuario;
			}
			set
			{
				if ((this._Idusuario != value))
				{
					this._Idusuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="NChar(10)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_productos", DbType="VarChar(50)")]
		public string productos
		{
			get
			{
				return this._productos;
			}
			set
			{
				if ((this._productos != value))
				{
					this._productos = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Precio", DbType="Float")]
		public System.Nullable<double> Precio
		{
			get
			{
				return this._Precio;
			}
			set
			{
				if ((this._Precio != value))
				{
					this._Precio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(50)")]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this._Descripcion = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.View_TOTAL_A_PAGAR")]
	public partial class View_TOTAL_A_PAGAR
	{
		
		private System.Nullable<double> _total;
		
		private int _Idusuario;
		
		public View_TOTAL_A_PAGAR()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_total", DbType="Float")]
		public System.Nullable<double> total
		{
			get
			{
				return this._total;
			}
			set
			{
				if ((this._total != value))
				{
					this._total = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Idusuario", DbType="Int NOT NULL")]
		public int Idusuario
		{
			get
			{
				return this._Idusuario;
			}
			set
			{
				if ((this._Idusuario != value))
				{
					this._Idusuario = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
